### ISSUE TITLE
[Bug] Comparing hashes only is not enough

### ISSUE THREAD

**Issue by DenChetverikov** [Manu343726/ctti#14]
`
        friend constexpr bool operator==(const type_id_t& lhs, const type_id_t& rhs)
        {
            return lhs.hash() == rhs.hash() && lhs.name_ == rhs.name_;
        }
`
If hashes are identical, names could be still different, due to collision. Code above is a fix.

**Comment by Manu343726** [comment]
While I agree, the whole library depends on the strength of the hash function and that no collisions between types "would" occur, so while I agree with you this could be a problem (and your snippet a solution) many other tings would be broken in that situation. Consider for example ` ctti::unnamed_type_id_t`, an Id type that was explicitly added to not having the memory overhead of the name literal in all contexts using type ids, basically storing just the hash. In that case the solution you propose cannot be applied.

Since `type_id` and `unnammed_type_id` are supposed to be (and work) exactly the same with the difference of having more or less type info, I'm not going to change this bc I think the same behavior is expected in the two variants.

Anyway, thanks a lot for reporting the issue, and sorry for the (very) late response.
